# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://britchie345.github.io
title: Brian Ritchie
email: britchie345@gmail.com
author: Brian Ritchie
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: gmail
    url: britchie345@gmail.com
  - title: github
    url: https://github.com/britchie345
  - title: linkedin
    url: https://www.linkedin.com/in/brianritchie1
